### ISSUE TITLE
Build a release, please?

### ISSUE THREAD

**Issue by sapioit** [Griffon26/ReTextPortable#1]
Hi!

Could you, please, build a release for Windows? I mean with everything ready to go...

Also, if you haven't already, you should link in the original project to this one.

**Comment by matsuz** [comment]
Use embedded edition of python, with prebuild edition of pyqt5, and some other dependencies, maybe just set `PYTHONPATH`, you can get a package for window in easy way. And all are green.

The prebuild wheel of pyqt5 for windows can be got from pypi.

**Comment by 2wayne** [comment]
I've created a Development Test here: https://portableapps.com/node/56132

**Comment by sapioit** [comment]
Thanks!

**Comment by Griffon26** [comment]
I just built a release. @2wayne if you're still actively working on your PortableApps version, perhaps we can work together.

@sapioit what did you mean by linking in the original project?

**Comment by sapioit** [comment]
@Griffon26 I meant linking to the not-portable ReText.

And thanks for building the release!
