### ISSUE TITLE
Update the instruction to use PyQt wheels

### ISSUE THREAD

**Issue by mitya57** [Griffon26/ReTextPortable#2]
The instruction currently says:

> 5. Install [`PyQt5-5.5.1-gpl-Py3.4-Qt5.5.1-x32.exe`][5] from riverbankcomputing.com into `ReTextPortable\App\python` (the "Minimal" install will suffice)

[5]: https://www.riverbankcomputing.com/software/pyqt/download5

However riverbankcomputing no longer ships binary installers for new PyQt5 releases. Instead, it ships [wheels on PyPI](https://pypi.python.org/pypi/PyQt5), available for both 32-bit and 64-bit Windows.

I guess it would be easy to use them instead of the installer, what do you think @Griffon26?

(Or do you think we should stick to PyQt 5.5.1 because it contains WebKit? In that case maybe it will make sense to update the download link to [this page](https://sourceforge.net/projects/pyqt/files/PyQt5/PyQt-5.5.1/).)

**Comment by Griffon26** [comment]
Updated to install everything from PyPI, so this is now solved.
